package com.automation.enums;

public enum ConfigProperties {
	
	URL,
	OVERRIDEREPORTS,
	PASSED_STEP_SCREENSHOTS,
	FAILED_STEP_SCREENSHOTS,
	SKIPPED_STEP_SCREENSHOTS,
	RETRY_FAILED_TESTS,
	RETRY_COUNT,
	RUNMODE
}
